version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
    container_name: jenkins
  cli:
    container_name: python_cli
    build:
      context: ./
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    command: "python calc.py"

    # working_dir: /app
#     volumes:
#       - app_data:C:\app

volumes:
  jenkins_home:
